version: '3'

services:
    run:
        container_name: local-althingi-store-run
        labels:
            - althingi_service=store
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ENV=development
                - IDE_KEY=VSCODE
        ports:
            - 8083:80
        environment:
            - STORE_DB_HOST=mongo
            - STORE_DB_USER=root
            - STORE_DB_PASSWORD=example
        volumes:
            - ./config:/var/app/config
            - ./src:/var/app/src
            - ./test:/var/app/test
            - ./vendor:/var/app/vendor
            - ./www:/var/app/www
            - ./composer.json:/var/app/composer.json
            - ./composer.lock:/var/app/composer.lock
        depends_on:
            - mongo

    test:
        container_name: local-althingi-store-test
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ENV=development
        environment:
            - STORE_DB_HOST=mongo
            - STORE_DB_USER=root
            - STORE_DB_PASSWORD=example
        volumes:
            - ./config:/var/app/config
            - ./src:/var/app/src
            - ./test:/var/app/test
            # - ./vendor:/var/app/vendor
            - ./www:/var/app/www
            - ./phpunit.xml.dist:/var/app/phpunit.xml
            - ./composer.json:/var/app/composer.json
            - ./composer.lock:/var/app/composer.lock
            - ./wait-for.sh:/var/app/wait-for.sh
        depends_on:
            - mongo-test
        command: bash -c "./wait-for.sh mongo-test:27017 -t 80 -- echo \"MongoDB up\" &&  ./vendor/bin/phpunit ./test/"

    mongo:
        container_name: local-althingi-store-db
        image: bitnami/mongodb:6.0.1
        restart: always
        environment:
            MONGODB_ROOT_USER: root
            MONGODB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes:
            - local-store-db-volume:/bitnami/mongodb

    mongo-test:
        container_name: local-althingi-store-db-test
        image: bitnami/mongodb:6.0.1
        restart: always
        environment:
            MONGODB_ROOT_USER: root
            MONGODB_ROOT_PASSWORD: example


volumes:
    local-store-db-volume:
